@startuml Login
Browser -> Server: login
Server -> Browser: redirect to Auth /
Browser -> Auth: request /
Auth -> D1: store session
Auth -> Browser: redirect to Google login
Browser -> Google: login
Google -> Browser: redirect to Auth /callback
Browser -> Auth: request /callback
Auth -> D1: get session
Auth -> Auth: verify session
Auth -> Google: get user info
Google -> Auth: user info
Auth -> D1: store exchange code
Auth -> Browser: redirect to Server /callback
Browser -> Server: request /callback
Server -> Auth: exchange token
Auth -> D1: get exchange code
Auth -> Auth: generate token
Auth -> KV: store hash(token)
Auth -> Server: token
Server -> Browser: redirect to authenticated page with token
@enduml
