name = "deploys-app--auth"
main = "src/index.js"
compatibility_date = "2023-09-22"
node_compat = true

[vars]

[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database = "deploys-app--auth"
database_id = "65fbdd15-b212-414f-8c4b-339108469ee3"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "a7b66b1bc1f3482383e449c7f54fc716"

[[analytics_engine_datasets]]
binding = "WAE"
dataset = "DEPLOYS_AUTH"
